# configs/expseek_zero.yaml

# ======= Mode =======
compute_entropy: true
need_guidance: true
use_guide_model: true
zero_exp: true
ablate: full
guidance_interval: 1

# ======= Entropy Model =======
entropy_devices: "2,3"
entropy_model_path: xxx/Qwen3-8B
entropy_model_str: Qwen3-8B
process_start: 0.314
process_end: 0.413
final_start: 0.225
final_end: 0.257

# ======= Experience KB =======
exp_kb_path: "" 

# ======= Guide Model =======
guide_model_name: qwen3-30b-a3b-instruct-2507
guide_api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
guide_api_key: sk-xxx

# ======= Inference Model =======
model_mode: vllm
model_name: Qwen3-8B
api_base: http://localhost:8012/v1
api_key: EMPTY
temperature: 1
top_p: 0.95

# ======= Summary Model =======
sum_model_name: qwen3-235b-a22b-instruct-2507
sum_api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
sum_api_key: sk-xxx

# ======= Run Settings =======
time_stamp: now
dataset: gaia
use_debug: false
roll_out_count: 5
max_retries: 3
max_workers: 5
max_call_per_run: 30
response_budget: 500
max_tokens: 32768

# ======= Tools =======
visit_path: expseek/tools/visit_memory.jsonl
jina_key: jina_xxx
brightdata_key: xxx
brightdata_zone: xxx
brightdata_location: en

# ======= Unused =======
embedding_kb_path: ""
